# Generated by Django 4.2.6 on 2023-11-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otpdevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpdevice',
            old_name='user',
            new_name='otp_device',
        ),
    ]
