# Generated by Django 4.2.6 on 2023-11-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_otpdevice_otp_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpdevice',
            old_name='otp_device',
            new_name='otp',
        ),
    ]
