# Generated by Django 4.2.6 on 2023-11-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_otp_device_otpdevice_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPDevice',
        ),
    ]
