# Generated by Django 4.2.6 on 2023-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_amount_per_user',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
