# Generated by Django 4.2.6 on 2023-11-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0002_expense_split_amount_per_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='split_amount_per_user',
            new_name='amount_lent_by_user',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_paid_by_user',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
