# Generated by Django 4.2.6 on 2023-11-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0003_userexpense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExpense',
        ),
    ]
