# Generated by Django 4.2.6 on 2023-11-07 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spliterapp', '0003_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='split_with',
            field=models.ManyToManyField(related_name='split_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
