# Generated by Django 4.2.6 on 2023-11-07 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spliterapp', '0004_expense_split_amount_expense_split_with'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='group_by',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_with',
            field=models.ManyToManyField(related_name='expenses_involved', to=settings.AUTH_USER_MODEL),
        ),
    ]
