# Generated by Django 4.2.6 on 2023-11-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0005_lentto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LentTo',
        ),
    ]
