# Generated by Django 4.2.6 on 2023-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0006_delete_lentto'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total_amount_paid_by_user',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
