# Generated by Django 4.2.6 on 2023-11-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0009_repayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repayment',
        ),
    ]
