# Generated by Django 4.2.6 on 2023-11-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0010_delete_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='settle_up',
            field=models.BooleanField(default=False),
        ),
    ]
