# Generated by Django 4.2.6 on 2023-11-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0011_expense_settle_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='settle_up',
        ),
    ]
