# Generated by Django 4.2.6 on 2023-12-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0014_repayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
