# Generated by Django 4.2.6 on 2023-12-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0015_rename_amount_expense_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount_lent_by_user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='amount_paid_by_user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='paid_by_name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='total_amount',
        ),
    ]
