# Generated by Django 4.2.6 on 2023-12-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0018_repaymentdetail_delete_repayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repaymentdetail',
            name='expense',
        ),
    ]
