# Generated by Django 4.2.6 on 2023-12-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0019_remove_repaymentdetail_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='percentages',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
