# Generated by Django 4.2.6 on 2023-12-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0021_alter_expense_split_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount_lent_by_user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='amount_paid_by_user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='total_amount_paid_by_activeuser',
        ),
    ]
