# Generated by Django 4.2.6 on 2023-12-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0022_remove_expense_amount_lent_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_lent_by_user',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_paid_by_user',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_amount_paid_by_activeuser',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
