# Generated by Django 4.2.6 on 2023-12-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spliterapp', '0023_expense_amount_lent_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='split_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
